services:
  - type: web
    name: verbo-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: verbo-backend
          property: port
    autoDeploy: true
    healthCheckPath: /api/health
